/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SecureVaultInheritance } from "./SecureVaultInheritance";
export * as factories from "./factories";
export { SecureVaultInheritance__factory } from "./factories/SecureVaultInheritance__factory";
