/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SecureVaultInheritance {
  export type AssetStruct = {
    assetHash: string;
    owner: AddressLike;
    nominee: AddressLike;
    lastActive: BigNumberish;
    inactivityPeriod: BigNumberish;
    exists: boolean;
    claimed: boolean;
  };

  export type AssetStructOutput = [
    assetHash: string,
    owner: string,
    nominee: string,
    lastActive: bigint,
    inactivityPeriod: bigint,
    exists: boolean,
    claimed: boolean
  ] & {
    assetHash: string;
    owner: string;
    nominee: string;
    lastActive: bigint;
    inactivityPeriod: bigint;
    exists: boolean;
    claimed: boolean;
  };
}

export interface SecureVaultInheritanceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "assets"
      | "claimAsset"
      | "getAsset"
      | "registerAsset"
      | "triggerInheritance"
      | "updateLastActive"
      | "updateLastActiveForUser"
      | "userLastActive"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActivityUpdated"
      | "AssetRegistered"
      | "InheritanceTriggered"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "assets", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "claimAsset",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getAsset", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "registerAsset",
    values: [string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerInheritance",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLastActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateLastActiveForUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userLastActive",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "assets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimAsset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerInheritance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLastActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLastActiveForUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userLastActive",
    data: BytesLike
  ): Result;
}

export namespace ActivityUpdatedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetRegisteredEvent {
  export type InputTuple = [
    assetId: BytesLike,
    assetHash: string,
    owner: AddressLike,
    nominee: AddressLike
  ];
  export type OutputTuple = [
    assetId: string,
    assetHash: string,
    owner: string,
    nominee: string
  ];
  export interface OutputObject {
    assetId: string;
    assetHash: string;
    owner: string;
    nominee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InheritanceTriggeredEvent {
  export type InputTuple = [
    assetId: BytesLike,
    owner: AddressLike,
    nominee: AddressLike
  ];
  export type OutputTuple = [assetId: string, owner: string, nominee: string];
  export interface OutputObject {
    assetId: string;
    owner: string;
    nominee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [assetId: BytesLike, newOwner: AddressLike];
  export type OutputTuple = [assetId: string, newOwner: string];
  export interface OutputObject {
    assetId: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SecureVaultInheritance extends BaseContract {
  connect(runner?: ContractRunner | null): SecureVaultInheritance;
  waitForDeployment(): Promise<this>;

  interface: SecureVaultInheritanceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assets: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean, boolean] & {
        assetHash: string;
        owner: string;
        nominee: string;
        lastActive: bigint;
        inactivityPeriod: bigint;
        exists: boolean;
        claimed: boolean;
      }
    ],
    "view"
  >;

  claimAsset: TypedContractMethod<[_assetId: BytesLike], [void], "nonpayable">;

  getAsset: TypedContractMethod<
    [_assetId: BytesLike],
    [SecureVaultInheritance.AssetStructOutput],
    "view"
  >;

  registerAsset: TypedContractMethod<
    [
      _assetHash: string,
      _nominee: AddressLike,
      _inactivityPeriod: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  triggerInheritance: TypedContractMethod<
    [_assetId: BytesLike],
    [void],
    "nonpayable"
  >;

  updateLastActive: TypedContractMethod<[], [void], "nonpayable">;

  updateLastActiveForUser: TypedContractMethod<
    [_user: AddressLike],
    [void],
    "nonpayable"
  >;

  userLastActive: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assets"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean, boolean] & {
        assetHash: string;
        owner: string;
        nominee: string;
        lastActive: bigint;
        inactivityPeriod: bigint;
        exists: boolean;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimAsset"
  ): TypedContractMethod<[_assetId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAsset"
  ): TypedContractMethod<
    [_assetId: BytesLike],
    [SecureVaultInheritance.AssetStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerAsset"
  ): TypedContractMethod<
    [
      _assetHash: string,
      _nominee: AddressLike,
      _inactivityPeriod: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "triggerInheritance"
  ): TypedContractMethod<[_assetId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateLastActive"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateLastActiveForUser"
  ): TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userLastActive"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "ActivityUpdated"
  ): TypedContractEvent<
    ActivityUpdatedEvent.InputTuple,
    ActivityUpdatedEvent.OutputTuple,
    ActivityUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AssetRegistered"
  ): TypedContractEvent<
    AssetRegisteredEvent.InputTuple,
    AssetRegisteredEvent.OutputTuple,
    AssetRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "InheritanceTriggered"
  ): TypedContractEvent<
    InheritanceTriggeredEvent.InputTuple,
    InheritanceTriggeredEvent.OutputTuple,
    InheritanceTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "ActivityUpdated(address,uint256)": TypedContractEvent<
      ActivityUpdatedEvent.InputTuple,
      ActivityUpdatedEvent.OutputTuple,
      ActivityUpdatedEvent.OutputObject
    >;
    ActivityUpdated: TypedContractEvent<
      ActivityUpdatedEvent.InputTuple,
      ActivityUpdatedEvent.OutputTuple,
      ActivityUpdatedEvent.OutputObject
    >;

    "AssetRegistered(bytes32,string,address,address)": TypedContractEvent<
      AssetRegisteredEvent.InputTuple,
      AssetRegisteredEvent.OutputTuple,
      AssetRegisteredEvent.OutputObject
    >;
    AssetRegistered: TypedContractEvent<
      AssetRegisteredEvent.InputTuple,
      AssetRegisteredEvent.OutputTuple,
      AssetRegisteredEvent.OutputObject
    >;

    "InheritanceTriggered(bytes32,address,address)": TypedContractEvent<
      InheritanceTriggeredEvent.InputTuple,
      InheritanceTriggeredEvent.OutputTuple,
      InheritanceTriggeredEvent.OutputObject
    >;
    InheritanceTriggered: TypedContractEvent<
      InheritanceTriggeredEvent.InputTuple,
      InheritanceTriggeredEvent.OutputTuple,
      InheritanceTriggeredEvent.OutputObject
    >;

    "OwnershipTransferred(bytes32,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
