"""
Domain Value Objects & Enumerations — SecureVault Enterprise
Core constants, types, and statuses across the platform.
"""

from enum import Enum


class VaultState(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE_WARNING_1 = "INACTIVE_WARNING_1"
    INACTIVE_WARNING_2 = "INACTIVE_WARNING_2"
    CLAIM_INITIATED = "CLAIM_INITIATED"
    CLAIM_HALTED = "CLAIM_HALTED"
    COOLING_PERIOD = "COOLING_PERIOD"
    NOMINEE_VERIFICATION = "NOMINEE_VERIFICATION"
    ADMIN_REVIEW = "ADMIN_REVIEW"
    DUAL_APPROVAL_PENDING = "DUAL_APPROVAL_PENDING"
    KEY_RELEASE_GRANTED = "KEY_RELEASE_GRANTED"
    ASSET_RELEASED = "ASSET_RELEASED"
    CLAIM_REJECTED = "CLAIM_REJECTED"


class AssetCategory(str, Enum):
    DOCUMENTS = "DOCUMENTS"
    CREDENTIALS = "CREDENTIALS"
    FINANCIAL = "FINANCIAL"
    LEGAL = "LEGAL"
    INSURANCE = "INSURANCE"
    PROPERTY = "PROPERTY"
    CRYPTO = "CRYPTO"
    IDENTITY = "IDENTITY"
    EMERGENCY = "EMERGENCY"
    BUSINESS = "BUSINESS"
    PHOTOS = "PHOTOS"
    VIDEOS = "VIDEOS"
    NOTES = "NOTES"
    PERSONAL = "PERSONAL"


class SensitivityLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AssetStatus(str, Enum):
    CREATED = "CREATED"
    ACTIVE = "ACTIVE"
    UPDATED = "UPDATED"
    LOCKED = "LOCKED"
    RELEASE_PENDING = "RELEASE_PENDING"
    RELEASED = "RELEASED"
    ARCHIVED = "ARCHIVED"


class NomineeType(str, Enum):
    PRIMARY = "PRIMARY"
    CONTINGENT = "CONTINGENT"
    SECONDARY = "SECONDARY"
    BACKUP = "BACKUP"
    EXECUTOR = "EXECUTOR"
    GUARDIAN = "GUARDIAN"
    EMERGENCY_CONTACT = "EMERGENCY_CONTACT"
    PROFESSIONAL = "PROFESSIONAL"


class NomineeStatus(str, Enum):
    INVITED = "INVITED"
    ACCEPTED = "ACCEPTED"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    REVOKED = "REVOKED"
    PENDING = "PENDING"
    INACTIVE = "INACTIVE"


class ReleaseCondition(str, Enum):
    IMMEDIATE_ON_CLAIM = "IMMEDIATE_ON_CLAIM"
    AFTER_COOLING_PERIOD = "AFTER_COOLING_PERIOD"
    DUAL_APPROVAL_REQUIRED = "DUAL_APPROVAL_REQUIRED"
    MANUAL_ADMIN_RELEASE = "MANUAL_ADMIN_RELEASE"


class ClaimStatus(str, Enum):
    NEW = "NEW"
    ASSIGNED = "ASSIGNED"
    UNDER_REVIEW = "UNDER_REVIEW"
    WAITING_DOCUMENTS = "WAITING_DOCUMENTS"
    ESCALATED = "ESCALATED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CLOSED = "CLOSED"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ApprovalType(str, Enum):
    SINGLE = "SINGLE"
    DUAL = "DUAL"
    MULTI = "MULTI"
    SUPERVISOR = "SUPERVISOR"


class JobStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    RETRYING = "RETRYING"
    DEAD_LETTER = "DEAD_LETTER"


class AdminRole(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    COMPLIANCE_OFFICER = "COMPLIANCE_OFFICER"
    SECURITY_ADMIN = "SECURITY_ADMIN"
    SUPPORT_ADMIN = "SUPPORT_ADMIN"
